### ISSUE TITLE
Artikler - Byggesystem?

### ISSUE THREAD

**Issue by themkat** [ryfylke-react-as/koding.no#16]
Når man har kommet forbi det absolutt enkleste, begynner å bruke litt avhengigheter osv., så kommer man fort borti byggesystem. Byggesystem i denne konteksten tenker jeg på som Maven, Gradle, NPM, Cargo osv. 

Tanken min er noe ala:
- **Hvorfor bruker vi byggesystem?** (enkelte har kanskje kun kompilert/kjørt direkte med python, javac, kotlinc, node, nettleser osv., og kan kanskje lure på hvorfor de trenger dette)
- **Oppgaver et slikt program ofte løser** (f.eks nevne dependencies, testkjøringer, bygging, lage "utgivbar" applikasjoner som andre kan kjøre uten for mye hazzle osv. "Transitive avhengigheter" kan nok nevnes her for å få opp litt øyne. Bare passe på å gjøre det på en måte som ikke virker for kompleks)
- **Eksempler på byggesystem du finner der ute**

Litt usikker på hvordan jeg ville strukturert dette for øyeblikket, eller hva det kalles på norsk 🙁 Tenker jeg lufter dette i tilfelle noen har tanker eller føler skrivekløe.

**Comment by imp-dance** [comment]
> Litt usikker på hvordan jeg ville strukturert dette for øyeblikket, eller hva det kalles på norsk 

Jeg tror byggsystem er et fint ord for konseptet! **CI** kunne potensielt vært en grei kategori å legge det i, selv om man ikke nødvendigvis alltid bygger i CI. Litt usikker selv på hvordan man bør organisere det, men det er ingenting i veien for å legge den på toppnivå under artikler for så å på sikt flytte på den hvis det dukker opp en passende kategori.

**Comment by themkat** [comment]
@imp-dance , supert! Da begynner jeg på en liten artikkel om dette 🙂
