### ISSUE TITLE
Legge til lisens

### ISSUE THREAD

**Issue by audunmo** [ryfylke-react-as/koding.no#2]
Heisann, fett prosjekt. Om det skal være open source, så må det lisensieres som det, dvs du må legge på en LICENSE.md med en open source lisens. Ellers så er det forsatt kode som ingen andre kan bruke, selvom vi teknisk sett kan laste den ned og åpne PRer. En populær en er MIT, men finnes mange lisenser med forskjellige trase-offs. Denne nettsiden kan hjelpe deg med å velge 😊 https://choosealicense.com

**Comment by imp-dance** [comment]
Godt poeng! Jeg legger til en MIT lisens via PR #3 👍
