### ISSUE TITLE
meta: Beskrivelse og flere tags for å gjøre søking gjennom Github enklere

### ISSUE THREAD

**Issue by themkat** [ryfylke-react-as/koding.no#24]
Akkurat nå er forhåndsvisningen av siden veldig anonym om man f.eks viser den i pinned repositories:
![image](https://github.com/ryfylke-react-as/koding.no/assets/5732795/6a6c8680-3f00-432b-b39f-296e3cc1658a)
(og andre steder der den vises)

Tenker at selv første setning fra readme'en i en eller annen form kan øke førsteinntrykket litt. Noe ala: "Open-source norsk nettside som har som hovedmål å veilede nye utviklere mot selvstyrt læring innen koding" 🙂 

Til ref ser min personlige nettside sin forhåndsvisning slik ut:
![image](https://github.com/ryfylke-react-as/koding.no/assets/5732795/5f7ab06c-073c-48d2-ab41-2e21376f0c3a)

Å legge til litt flere relevante tags kan også gjøre det lettere å finne prosjektet. Forslag til tags: norsk, norge, teaching-materials, learn-to-code, learning, self-taught
(sikkert flere også)

Vær gjerne uenig. Dette er jo veldig subjektivt hva jeg føler kunne hjulpet folk å finne repoet 🙂

**Comment by imp-dance** [comment]
Godt poeng! Skal være ordnet nå 😄
